name: Tests

on: [pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.4]
        stability: [prefer-lowest, prefer-stable]

    name: PHP-${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }} - PHPUnit

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: "dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo"
          coverage: none

      - name: Configure Plugins flex
        run: composer config --no-plugins allow-plugins.symfony/flex true

      - name: Configure Plugins runtime
        run: composer config --no-plugins allow-plugins.symfony/runtime true

      - name: Configure Plugins http-discovery
        run: composer config --no-plugins allow-plugins.php-http/discovery true

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: bin/phpunit
